const API_URL="https://script.google.com/macros/s/AKfycbwCN39HHbwgo92ItpTXazCzkblFZHn7m3zhnLkGh7qQUqFoescOPRY58xu_uTkVwUF8HQ/exec";
let lastFeedbackText="",lastCorrectSentence="",continuousMode=false;
let session={started:Date.now(),answers:0,words:0,errors:0};

const questions=["Tell me about your day.","What did you do yesterday?","What are your plans for tomorrow?","Describe your job in three sentences.","Tell me about your favorite food.","What is difficult for you when you speak English?","Describe your city.","Tell me about your family."];
const dailyQuestions=["What did you do today?","What are you going to do tomorrow?","What was the best part of your week?","Tell me about your work routine.","What is something you want to improve?","Describe your morning routine.","Tell me about a person you admire."];
const examQuestions=["Describe a problem you solved recently.","Talk about a person who inspires you.","Describe your ideal vacation.","Explain why learning English is important for you.","Tell me about a difficult day at work."];
const shadows=["I want to improve my American pronunciation.","Could you say that again, please?","I usually go to work at eight.","Yesterday I worked all day and then I went home.","I feel more confident when I practice every day.","I would like to speak more naturally."];
const sounds=[{title:"TH sound: think / three / thank",tip:"Pon la punta de la lengua suavemente entre los dientes y sopla. No digas tink.",example:"think, three, thank you"},{title:"V sound: very / voice / vacation",tip:"Toca el labio inferior con los dientes superiores y vibra. No lo pronuncies como B.",example:"very good voice"},{title:"American R: car / work / teacher",tip:"Lleva la lengua hacia atrás sin tocar el paladar.",example:"car, work, teacher"},{title:"Final ED: worked / played / wanted",tip:"Worked suena T, played suena D, wanted suena ID.",example:"worked, played, wanted"}];

document.querySelectorAll(".tabs button").forEach(btn=>btn.addEventListener("click",()=>{document.querySelectorAll(".tabs button").forEach(b=>b.classList.remove("active"));document.querySelectorAll(".screen").forEach(s=>s.classList.remove("active"));btn.classList.add("active");document.getElementById(btn.dataset.screen).classList.add("active");if(btn.dataset.screen==="session")showSessionSummary();if(btn.dataset.screen==="plan")updatePlan();}));
function installApp(){alert("Para instalar la app en Android: toca los tres puntitos ⋮ de Chrome y elige “Agregar a pantalla principal”.");}
function clearLocalData(){localStorage.removeItem("marioV15Academy");alert("Datos locales borrados.");updateStats();}
function getText(id){return document.getElementById(id).textContent}function random(a){return a[Math.floor(Math.random()*a.length)]}
function marioIntro(){marioSpeak("Hi Mario! Welcome to Mario Coach AI version fifteen. I am your English academy teacher.","en-US")}
function startDailyClass(){document.querySelector('[data-screen="daily"]').click();newDaily();marioSpeak(getText("dailyQuestion"),"en-US")}
function newDaily(){document.getElementById("dailyQuestion").textContent=random(dailyQuestions)}
function newExam(){document.getElementById("examQuestion").textContent=random(examQuestions)}
function newShadow(){document.getElementById("shadowPhrase").textContent=random(shadows)}
function newSound(){const s=random(sounds);document.getElementById("soundTitle").textContent=s.title;document.getElementById("soundTip").textContent=s.tip}
function speakSound(){const s=sounds.find(x=>x.title===getText("soundTitle"))||sounds[0];marioSpeak(s.example,"en-US",.75)}

function marioSpeak(text,lang="es-ES",rate=.92,after=null){if(!("speechSynthesis"in window)){alert("Este navegador no permite voz.");return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(cleanSpeech(text));u.lang=lang;u.rate=rate;u.pitch=1;const voices=speechSynthesis.getVoices();const v=voices.find(x=>x.lang===lang)||voices.find(x=>x.lang&&x.lang.startsWith(lang.split("-")[0]));if(v)u.voice=v;const avatar=document.getElementById("avatar");u.onstart=()=>avatar.classList.add("speaking");u.onend=()=>{avatar.classList.remove("speaking");if(after)after()};u.onerror=()=>avatar.classList.remove("speaking");speechSynthesis.speak(u)}
function cleanSpeech(t){return String(t).replace(/[✅🎙️🧠🇺🇸👨🏻‍🏫⭐📊🏆🎯]/g," ").replace(/\*/g,"").replace(/\s+/g," ").trim()}
function speakTeacherReply(t){marioSpeak(t.replace(/Mario says:/g,"Mario dice:").replace(/Natural American English:/g,"La versión natural en inglés americano es:").replace(/Explicación simple:/g,"Explicación simple:").replace(/Pronunciation tip:/g,"Consejo de pronunciación:").replace(/Next question:/g,"Siguiente pregunta:"),"es-ES",.92,()=>{if(continuousMode)nextAutoQuestion()})}
function speakLastFeedback(){if(!lastFeedbackText){alert("Primero hacé una corrección.");return}speakTeacherReply(lastFeedbackText)}
function repeatCorrectSentence(){if(!lastCorrectSentence){alert("Todavía no encontré una frase correcta.");return}marioSpeak(lastCorrectSentence,"en-US",.78)}

function listenTo(id){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){alert("Tu navegador no permite reconocimiento de voz. Escribe tu respuesta.");return}const rec=new SR();rec.lang="en-US";rec.interimResults=false;rec.continuous=false;rec.onresult=e=>{document.getElementById(id).value=Array.from(e.results).map(r=>r[0].transcript).join(" ");estimateScores(document.getElementById(id).value)};rec.onerror=e=>alert("Error de micrófono: "+e.error);rec.start()}
function estimateScores(text){const words=String(text).trim().split(/\s+/).filter(Boolean).length;const pron=Math.min(98,Math.max(45,58+words*3+Math.floor(Math.random()*10)));const grammar=Math.min(98,Math.max(50,70+Math.floor(Math.random()*20)));setScores(pron,grammar);return {pron,grammar}}
function setScores(p,g){document.getElementById("pronBar").style.width=p+"%";document.getElementById("pronScore").textContent=p+"%";document.getElementById("grammarBar").style.width=g+"%";document.getElementById("grammarScore").textContent=g+"%"}

async function callMarioAI(text,mode){const res=await fetch(API_URL,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify({text,mode})});const data=await res.json();if(data.error)throw new Error(data.error);return data.reply}
function handleReply(id,reply,words=0,score=90,xp=20){lastFeedbackText=reply;lastCorrectSentence=extractCorrectSentence(reply);document.getElementById(id).textContent=reply;session.answers++;session.words+=words;session.errors+=countErrors(reply);speakTeacherReply(reply);addProgress(words,score,xp)}
async function correctDaily(){const text=document.getElementById("dailyAnswer").value.trim();if(!text){document.getElementById("dailyFeedback").textContent="Primero responde.";return}document.getElementById("dailyFeedback").textContent="Mario está corrigiendo...";try{const s=estimateScores(text);const r=await callMarioAI(text,"V15 Pro Academy daily class. Correct all errors, explain by voice, give next question.");handleReply("dailyFeedback",r,text.split(/\s+/).length,s.pron,35)}catch(e){document.getElementById("dailyFeedback").textContent=e.message}}
async function gradeExam(){const text=document.getElementById("examAnswer").value.trim();if(!text){document.getElementById("examFeedback").textContent="Primero responde.";return}document.getElementById("examFeedback").textContent="Mario evalúa...";try{const s=estimateScores(text);const r=await callMarioAI(text,"V15 Pro Academy B1/B2 speaking exam. Include CEFR, score, vocabulary upgrade, next goal.");handleReply("examFeedback",r,text.split(/\s+/).length,s.pron,50)}catch(e){document.getElementById("examFeedback").textContent=e.message}}
async function sendChat(){const input=document.getElementById("chatInput");const text=input.value.trim();if(!text)return;addBubble("user","<b>You:</b> "+esc(text));input.value="";addBubble("mario","<b>Mario:</b> Thinking...");try{const s=estimateScores(text);const r=await callMarioAI(text,"V15 Pro Academy continuous conversation. Correct naturally and ask next question.");document.querySelector("#chat .bubble:last-child").innerHTML="<b>Mario:</b> "+esc(r).replace(/\n/g,"<br>");lastFeedbackText=r;lastCorrectSentence=extractCorrectSentence(r);session.answers++;session.words+=text.split(/\s+/).length;speakTeacherReply(r);addProgress(text.split(/\s+/).length,s.pron,25)}catch(e){document.querySelector("#chat .bubble:last-child").innerHTML="<b>Mario:</b> "+esc(e.message)}}
function startContinuousMode(){continuousMode=true;document.querySelector('[data-screen="conversation"]').click();const q=random(questions);addBubble("mario","<b>Mario:</b> "+esc(q));marioSpeak(q,"en-US")}
function stopContinuousMode(){continuousMode=false;alert("Modo continuo detenido.")}
function nextAutoQuestion(){const q=extractNextQuestion(lastFeedbackText)||random(questions);addBubble("mario","<b>Mario:</b> "+esc(q));marioSpeak(q,"en-US")}
function checkShadow(){const target=getText("shadowPhrase").toLowerCase().replace(/[^a-z\s]/g,"").trim();const ans=document.getElementById("shadowAnswer").value.toLowerCase().replace(/[^a-z\s]/g,"").trim();if(!ans){document.getElementById("shadowFeedback").textContent="Primero repite la frase.";return}const tw=target.split(/\s+/),aw=ans.split(/\s+/);const hits=tw.filter(w=>aw.includes(w)).length;const score=Math.round(hits/tw.length*100);setScores(score,90);addProgress(aw.length,score,15);const msg=`Coincidencia: ${score}%\nFrase correcta: ${getText("shadowPhrase")}\nRepite copiando ritmo, pausa y entonación.`;document.getElementById("shadowFeedback").textContent=msg;marioSpeak(msg,"es-ES")}
async function testApi(){const st=document.getElementById("apiStatus");st.textContent="Probando conexión...";try{const r=await callMarioAI("Hello Mario, this is a test.","V15 test");st.textContent="✅ Conexión correcta:\n"+r;marioSpeak("Conexión correcta. Mario Coach AI V15 está funcionando.","es-ES")}catch(e){st.textContent="❌ "+e.message}}
function updatePlan(){const p=loadProgress();const avg=p.scores.length?Math.round(p.scores.reduce((a,b)=>a+b,0)/p.scores.length):0;let plan=`🎯 Plan personalizado V15\n\n1. Practica 5 minutos de speaking diario.\n2. Repite la frase correcta 3 veces.\n3. Haz 1 ejercicio de shadowing.\n4. Viernes: mini examen B1/B2.\n\nTu promedio actual: ${avg}%\nMeta de esta semana: responder con frases más largas usando pasado simple.`;document.getElementById("planBox").textContent=plan;return plan}
function speakPlan(){marioSpeak(updatePlan(),"es-ES")}
function showSessionSummary(){const mins=Math.max(1,Math.round((Date.now()-session.started)/60000));const msg=`🏆 Resumen de sesión\n\nTiempo: ${mins} minuto(s)\nRespuestas: ${session.answers}\nPalabras practicadas: ${session.words}\nErrores detectados: ${session.errors}\n\nNivel sugerido: ${document.getElementById("level").textContent}\nPróxima meta: hablar más fluido usando pasado simple y conectores como then, after that, because.`;document.getElementById("sessionSummary").textContent=msg;return msg}
function speakSessionSummary(){marioSpeak(showSessionSummary(),"es-ES")}
function extractNextQuestion(t){const m=String(t).match(/Next question:\s*([^\n]+)/i);return m?m[1].trim():""}
function extractCorrectSentence(t){const m=String(t).match(/Natural American English:\s*["“]([^"”]+)["”]/i);if(m)return m[1].trim();const q=String(t).match(/["“]([^"”]{10,220})["”]/);return q?q[1].trim():""}
function countErrors(t){return (String(t).match(/error|mistake|cambio|corrección|incorrect|mejor/gi)||[]).length}
function addBubble(type,html){const chat=document.getElementById("chat");const div=document.createElement("div");div.className="bubble "+type;div.innerHTML=html;chat.appendChild(div);chat.scrollTop=chat.scrollHeight}
function loadProgress(){return JSON.parse(localStorage.getItem("marioV15Academy")||'{"xp":0,"sessions":0,"words":0,"scores":[],"lastDay":"","streak":0}')}
function saveProgress(p){localStorage.setItem("marioV15Academy",JSON.stringify(p));updateStats()}
function addProgress(words,score,xp){const p=loadProgress();const today=new Date().toDateString();if(p.lastDay!==today){p.streak=(p.lastDay?p.streak+1:1);p.lastDay=today}p.sessions++;p.words+=words;p.scores.push(score);p.xp+=xp;saveProgress(p)}
function updateStats(){const p=loadProgress();const avg=p.scores.length?Math.round(p.scores.reduce((a,b)=>a+b,0)/p.scores.length):0;document.getElementById("xp").textContent=p.xp;document.getElementById("streak").textContent=p.streak;document.getElementById("avg").textContent=avg;document.getElementById("level").textContent=avg>=90?"B2":avg>=80?"B1+":avg>=60?"B1":"A2"}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[m]))}
updateStats();updatePlan();
