const API_URL="https://script.google.com/macros/s/AKfycbwCN39HHbwgo92ItpTXazCzkblFZHn7m3zhnLkGh7qQUqFoescOPRY58xu_uTkVwUF8HQ/exec";
let lastFeedback="",lastSentence="",continuous=false;
let session={started:Date.now(),answers:0,words:0,errors:0};

const qs=["What did you do today?","What did you do yesterday?","What are your plans for tomorrow?","Tell me about your work routine.","Describe your family.","What is difficult for you in English?","Tell me about your city.","What did you eat today?"];
const exams=["Describe a problem you solved recently.","Talk about a person who inspires you.","Describe your ideal vacation.","Explain why English is important for you.","Tell me about a difficult day at work."];
const shadows=["I want to improve my American pronunciation.","Could you say that again, please?","Yesterday I worked all day and then I went home.","I feel more confident when I practice every day.","I would like to speak more naturally."];
const sounds=[{t:"TH sound: think / three / thank",tip:"Pon la punta de la lengua suavemente entre los dientes y sopla. No digas tink.",ex:"think, three, thank you"},{t:"V sound: very / voice / vacation",tip:"Toca el labio inferior con los dientes superiores y vibra. No lo pronuncies como B.",ex:"very good voice"},{t:"American R: car / work / teacher",tip:"Lleva la lengua hacia atrás sin tocar el paladar.",ex:"car, work, teacher"},{t:"Past ED: worked / played / wanted",tip:"Worked suena T, played suena D, wanted suena ID.",ex:"worked, played, wanted"}];

document.querySelectorAll(".tabs button").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll(".tabs button").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".screen").forEach(s=>s.classList.remove("active"));b.classList.add("active");document.getElementById(b.dataset.screen).classList.add("active");if(b.dataset.screen==="plan")updatePlan();if(b.dataset.screen==="summary")showSummary();}));
function getText(id){return document.getElementById(id).textContent} function rnd(a){return a[Math.floor(Math.random()*a.length)]}
function installApp(){alert("Para instalar en Android: Chrome ⋮ → Agregar a pantalla principal.");}
function intro(){speak("Hi Mario! Welcome to version sixteen. I will correct your English, explain your mistakes, score your speaking, and give you a personal plan.","en-US")}
function startDaily(){document.querySelector('[data-screen="class"]').click();newClass();speak(getText("classQuestion"),"en-US")}
function newClass(){document.getElementById("classQuestion").textContent=rnd(qs)}
function newExam(){document.getElementById("examQuestion").textContent=rnd(exams)}
function newShadow(){document.getElementById("shadowPhrase").textContent=rnd(shadows)}
function newSound(){let s=rnd(sounds);document.getElementById("soundTitle").textContent=s.t;document.getElementById("soundTip").textContent=s.tip}
function speakSound(){let s=sounds.find(x=>x.t===getText("soundTitle"))||sounds[0];speak(s.ex,"en-US",.75)}
function speak(text,lang="es-ES",rate=.92,after=null){if(!("speechSynthesis"in window)){alert("Este navegador no permite voz.");return}speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(clean(text));u.lang=lang;u.rate=rate;u.pitch=1;let vs=speechSynthesis.getVoices();let v=vs.find(x=>x.lang===lang)||vs.find(x=>x.lang&&x.lang.startsWith(lang.split("-")[0]));if(v)u.voice=v;let av=document.getElementById("avatar");u.onstart=()=>av.classList.add("speaking");u.onend=()=>{av.classList.remove("speaking");if(after)after()};u.onerror=()=>av.classList.remove("speaking");speechSynthesis.speak(u)}
function clean(t){return String(t).replace(/[✅🎙️🧠🇺🇸👨🏻‍🏫⭐📊🏆🎯📚🗣️]/g," ").replace(/\*/g,"").replace(/\s+/g," ").trim()}
function listenTo(id){let SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){alert("Tu navegador no permite reconocimiento de voz.");return}let r=new SR();r.lang="en-US";r.interimResults=false;r.continuous=false;r.onresult=e=>{document.getElementById(id).value=Array.from(e.results).map(x=>x[0].transcript).join(" ");scoreLocal(document.getElementById(id).value)};r.onerror=e=>alert("Error de micrófono: "+e.error);r.start()}
function scoreLocal(text){let w=String(text).trim().split(/\s+/).filter(Boolean).length;let g=Math.min(98,Math.max(55,68+Math.floor(Math.random()*24)));let p=Math.min(98,Math.max(45,58+w*3+Math.floor(Math.random()*8)));let f=Math.min(98,Math.max(50,60+w*2+Math.floor(Math.random()*12)));let v=Math.min(98,Math.max(55,65+Math.floor(Math.random()*25)));setScores(g,p,f,v);return Math.round((g+p+f+v)/4)}
function setScores(g,p,f,v){setBar("grammar",g);setBar("pron",p);setBar("fluency",f);setBar("vocab",v)}
function setBar(name,val){document.getElementById(name+"Bar").style.width=val+"%";document.getElementById(name+"Score").textContent=val+"%"}
async function ai(text,mode){let res=await fetch(API_URL,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify({text,mode})});let data=await res.json();if(data.error)throw new Error(data.error);return data.reply}
function promptMode(base){return base+" V16 FINAL. Give complete answer. Do not cut response. Include: Mario says, Natural American English, Error by error, Simple grammar rule, Pronunciation tip, CEFR estimate, score, next question."}
function handle(id,reply,text,score,xp){lastFeedback=reply;lastSentence=extractSentence(reply);document.getElementById(id).textContent=reply;session.answers++;session.words+=String(text).split(/\s+/).filter(Boolean).length;session.errors+=countErr(reply);addProgress(session.words,score,xp);speak(shortVoice(reply),"es-ES",.92,()=>{if(continuous)nextQuestion()})}
function shortVoice(t){let s=String(t);let natural=extractSentence(s);let q=extractQuestion(s);let exp=(s.match(/Explicación simple:\s*([\s\S]{0,350})/i)||s.match(/Error by error:\s*([\s\S]{0,350})/i)||["",""])[1];return `Muy bien. Esta es la versión natural: ${natural}. ${exp}. Ahora practica repitiendo la frase correcta. ${q? "Siguiente pregunta: "+q:""}`;}
async function correctClass(){let text=document.getElementById("classAnswer").value.trim();if(!text){document.getElementById("classFeedback").textContent="Primero responde.";return}document.getElementById("classFeedback").textContent="Mario está corrigiendo completo...";try{let score=scoreLocal(text);let r=await ai(text,promptMode("Daily class correction"));handle("classFeedback",r,text,score,35)}catch(e){document.getElementById("classFeedback").textContent=e.message}}
async function gradeExam(){let text=document.getElementById("examAnswer").value.trim();if(!text){document.getElementById("examFeedback").textContent="Primero responde.";return}document.getElementById("examFeedback").textContent="Mario está evaluando...";try{let score=scoreLocal(text);let r=await ai(text,promptMode("B1/B2 speaking exam. Include CEFR and score"));handle("examFeedback",r,text,score,50)}catch(e){document.getElementById("examFeedback").textContent=e.message}}
async function sendChat(){let inp=document.getElementById("chatInput");let text=inp.value.trim();if(!text)return;addBubble("user","<b>You:</b> "+esc(text));inp.value="";addBubble("mario","<b>Mario:</b> Thinking...");try{let score=scoreLocal(text);let r=await ai(text,promptMode("Continuous conversation"));document.querySelector("#chat .bubble:last-child").innerHTML="<b>Mario:</b> "+esc(r).replace(/\n/g,"<br>");lastFeedback=r;lastSentence=extractSentence(r);session.answers++;session.words+=text.split(/\s+/).length;addProgress(text.split(/\s+/).length,score,25);speak(shortVoice(r),"es-ES",.92,()=>{if(continuous)nextQuestion()})}catch(e){document.querySelector("#chat .bubble:last-child").innerHTML="<b>Mario:</b> "+esc(e.message)}}
function startContinuous(){continuous=true;document.querySelector('[data-screen="conversation"]').click();let q=rnd(qs);addBubble("mario","<b>Mario:</b> "+esc(q));speak(q,"en-US")}
function stopContinuous(){continuous=false;alert("Conversación continua detenida.")}
function nextQuestion(){let q=extractQuestion(lastFeedback)||rnd(qs);addBubble("mario","<b>Mario:</b> "+esc(q));speak(q,"en-US")}
function speakFeedback(){if(!lastFeedback){alert("Primero hacé una corrección.");return}speak(shortVoice(lastFeedback),"es-ES")}
function repeatSentence(){if(!lastSentence){alert("No encontré frase correcta.");return}speak(lastSentence,"en-US",.78)}
function checkShadow(){let t=getText("shadowPhrase").toLowerCase().replace(/[^a-z\s]/g,"").trim();let a=document.getElementById("shadowAnswer").value.toLowerCase().replace(/[^a-z\s]/g,"").trim();if(!a){document.getElementById("shadowFeedback").textContent="Primero repite la frase.";return}let tw=t.split(/\s+/),aw=a.split(/\s+/);let hits=tw.filter(w=>aw.includes(w)).length;let score=Math.round(hits/tw.length*100);setScores(90,score,score,85);let msg=`Coincidencia: ${score}%\nFrase correcta: ${getText("shadowPhrase")}\nRepite copiando ritmo, pausa y entonación.`;document.getElementById("shadowFeedback").textContent=msg;speak(msg,"es-ES");addProgress(aw.length,score,15)}
async function testApi(){let st=document.getElementById("apiStatus");st.textContent="Probando conexión...";try{let r=await ai("Hello Mario, this is a test.","V16 test");st.textContent="✅ Conexión correcta:\n"+r;speak("Conexión correcta. Mario Coach AI V16 está funcionando.","es-ES")}catch(e){st.textContent="❌ "+e.message}}
function updatePlan(){let p=loadProgress();let avg=p.scores.length?Math.round(p.scores.reduce((a,b)=>a+b,0)/p.scores.length):0;let plan=`🎯 Plan personalizado V16\n\nNivel actual: ${levelFrom(avg)}\nPromedio: ${avg}%\n\nEsta semana practica:\n1. Pasado simple: I went, I watched, I had.\n2. Conectores: then, after that, because.\n3. Shadowing 5 minutos por día.\n4. Una respuesta larga diaria de 5 oraciones.\n\nMeta: responder con frases completas y naturales.`;document.getElementById("planBox").textContent=plan;return plan}
function speakPlan(){speak(updatePlan(),"es-ES")}
function showSummary(){let mins=Math.max(1,Math.round((Date.now()-session.started)/60000));let msg=`🏆 Resumen V16\n\nTiempo: ${mins} minuto(s)\nRespuestas: ${session.answers}\nPalabras practicadas: ${session.words}\nErrores detectados: ${session.errors}\nNivel sugerido: ${document.getElementById("level").textContent}\n\nPróxima meta: hablar más fluido usando pasado simple y conectores.`;document.getElementById("summaryBox").textContent=msg;return msg}
function speakSummary(){speak(showSummary(),"es-ES")}
function extractSentence(t){let m=String(t).match(/Natural American English:\s*["“]([^"”]+)["”]/i);if(m)return m[1].trim();let q=String(t).match(/["“]([^"”]{10,250})["”]/);return q?q[1].trim():""}
function extractQuestion(t){let m=String(t).match(/Next question:\s*([^\n]+)/i);return m?m[1].trim():""}
function countErr(t){return (String(t).match(/error|mistake|incorrect|debe|cambio|corrección|mejor/gi)||[]).length}
function addBubble(type,html){let c=document.getElementById("chat");let d=document.createElement("div");d.className="bubble "+type;d.innerHTML=html;c.appendChild(d);c.scrollTop=c.scrollHeight}
function loadProgress(){return JSON.parse(localStorage.getItem("marioV16Final")||'{"xp":0,"scores":[],"lastDay":"","streak":0}')}
function saveProgress(p){localStorage.setItem("marioV16Final",JSON.stringify(p));updateStats()}
function addProgress(words,score,xp){let p=loadProgress();let today=new Date().toDateString();if(p.lastDay!==today){p.streak=(p.lastDay?p.streak+1:1);p.lastDay=today}p.xp+=xp;p.scores.push(score);saveProgress(p)}
function updateStats(){let p=loadProgress();let avg=p.scores.length?Math.round(p.scores.reduce((a,b)=>a+b,0)/p.scores.length):0;document.getElementById("xp").textContent=p.xp;document.getElementById("streak").textContent=p.streak;document.getElementById("avg").textContent=avg;document.getElementById("level").textContent=levelFrom(avg)}
function levelFrom(avg){return avg>=92?"B2+":avg>=85?"B2":avg>=75?"B1+":avg>=60?"B1":"A2"}
function clearData(){localStorage.removeItem("marioV16Final");updateStats();alert("Datos borrados.")}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[m]))}
updateStats();updatePlan();
